handle hc files

diff --git a/bin/mp4 b/bin/mp4
--- a/bin/mp4
+++ b/bin/mp4
@@ -1,20 +1,38 @@
 #!/usr/bin/env bash
+# TODO: Handle new files
 
 if [[ ! -f "${HOME}/.mp4" ]]; then
   printf '%s' "index=0" >"${HOME}/.mp4"
 fi
 
+# shellcheck source=/dev/null
 source "${HOME}/.mp4"
+combined=""
 
 if [[ ! -f "${HOME}/.mp4_list.gpg" ]] || [[ "${index}" == 0 ]]; then
-  gpg --yes --pinentry-mode loopback --output "${HOME}/.mp4_list.gpg" --symmetric < <(fd mp4 /media | shuf)
+  nonhc=$(fd mp4 /media --exclude '*hc_*' | shuf)
+  hc=$(fd ^hc_ /media | shuf)
+  counthc=$(echo "$hc" | wc -l)
+  counter=0
+  while read -r; do
+    combined+="${REPLY}\n"
+    (( counter++ ))
+    if [[ $counter -gt $counthc ]]; then
+        hc=$(echo "$hc" | shuf)
+        counter=1
+    fi
+    if [[ $(( counter % 2 )) -eq 0 ]]; then
+        combined+="$(echo "${hc}" | sed -n "${counter}"p)\n"
+    fi
+  done < <(echo "${nonhc}")
+  gpg --yes --pinentry-mode loopback --output "${HOME}/.mp4_list.gpg" --symmetric < <(echo -e "${combined}" | sed -e '/^$/d')
 fi
 
 list=$(gpg --pinentry-mode loopback -qd "${HOME}/.mp4_list.gpg")
 count=$(echo "${list}" | wc -l)
 
 if [[ $index -ge $count ]]; then
-    index=0
+  index=0
 fi
 
 if [[ -n "${list}" ]]; then
@@ -26,8 +44,8 @@ if [[ -n "${list}" ]]; then
       printf '%s' "index=$((last_index + index < count ? last_index + index - 1 : 0))" >"${HOME}/.mp4"
     fi
   else
-      echo "Checking the first file for existence failed. Maybe not mounted yet?"
-      exit 1
+    echo "Checking the first file for existence failed. Maybe not mounted yet?"
+    exit 1
   fi
 else
   echo "${HOME}/.mp4_list.gpg is empty."
